name: Convert Butane to Ignition on Push

on:
  push:
    paths:
      - 'ucore-autorebase.bu'
      - '.github/workflows/push-bu2ign.yml'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.PUSH2REP }}
      
      - name: Convert Butane to Ignition
        run: |
          podman run --interactive --rm quay.io/coreos/butane:release \
          --pretty --strict < ucore-autorebase.bu > ucore-autorebase.ign
          
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -f ucore-autorebase.ign
          git commit -m "Update Ignition config" || exit 0
          git push
